jenkins:
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      skipTlsVerify: true
      templates:
      - containers:
        - image: "maven:3.8.6-openjdk-8"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "maven"
          workingDir: "/home/jenkins/agent"
        - image: "gradle:8.4.0-jdk8"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "gradle"
          workingDir: "/home/jenkins/agent"
        - image: "docker:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "docker"
          workingDir: "/home/jenkins/agent"
        id: "382039d7-21dd-4c38-81e0-40322ff28af4"
        label: "kubeagent"
        name: "kube-agent"
        namespace: "jenkins"
        nodeUsageMode: "NORMAL"
        yamlMergeStrategy: "override"