name: Run Trivy scan on image

on:
  workflow_run:
    workflows: ["Build and push Docker image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile
          context: docker
          tags: jenkins-trivy-scan
          cache-from: type=registry,ref=andrar/jenkins:main

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jenkins-trivy-scan
          format: sarif
          output: trivy-results.sarif
          # severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-results.sarif